name = "portfolio"
# Choose a recent date; update periodically.
compatibility_date = "2025-09-12"

# Workers (deploy from Git) configuration
# - main worker script serves static assets and APIs
main = "dist/worker.mjs"

[observability.logs]
enabled = true

[placement]
mode = "smart"

# Bind static assets built by SPA to ASSETS within the Worker
[assets]
directory = ".tanstack/start/build/client-dist"
binding = "ASSETS"

# KV binding for rate limiting (optional but recommended). Create if needed:
# wrangler kv:namespace create RATE_LIMIT_KV
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "774fcd06999c4941addc72d16aa46280"

[vars]
# Any non-secret vars (client-exposed must be prefixed VITE_*)
VITE_SITE_VERSION = "1.0.0"
LASTFM_USER = "xo_supernova" # non-secret username for Last.fm proxy
VITE_APP_TITLE = "Nova Bowley"
VITE_APP_URL = "https://n0va.dev"
VITE_SITE_URL = "https://n0va.dev"
VITE_OG_IMAGE = "/img/icon.webp"
VITE_APP_TITLE_SHORT = "Nova"
VITE_APP_DESCRIPTION = "Personal portfolio for Nova Bowley"
VITE_APP_AUTHOR = "Nova Bowley"
VITE_APP_AUTHOR_SHORT = "Nova"
VITE_TURNSTILE_SITE_KEY = "0x4AAAAAAA6w1M7_zbGeb8tc" # set if using Turnstile widget
VITE_SOCIALS_GITHUB = "https://github.com/xosupernova"
VITE_SOCIALS_DISCORD = "https://discord.com/users/895595833540636682"
VITE_SOCIALS_EMAIL = "mailto:me@n0va.dev"
VITE_SOCIALS_X = "https://x.com/xosupernova"
VITE_SOCIALS_INSTAGRAM = "https://instagram.com/xo_supernova"
VITE_SOCIALS_LINKEDIN = "https://linkedin.com/in/xosupernova"
VITE_SOCIALS_FACEBOOK = "https://facebook.com/xosupernovaxox"
VITE_ENABLE_SENTRY = "false"
VITE_DISABLE_STRICT_MODE = "false"  # set to "true" to render without React.StrictMode (diagnostics)
VITE_ENABLE_DEVTOOLS = "false"      # set true to expose TanStack Router devtools in production build

# Secrets (set via: wrangler secret put DISCORD_WEBHOOK, TURNSTILE_SECRET, VITE_SENTRY_AUTH_TOKEN, etc.)
# DISCORD_WEBHOOK
# TURNSTILE_SECRET
# VITE_SENTRY_AUTH_TOKEN


# Environment overrides example
[env.preview]
[env.preview.vars]
VITE_APP_URL = "https://portfolio.pages.dev"
VITE_SITE_URL = "https://portfolio.pages.dev"
